# 基础清洗阈值、路径配置
# 路径配置
raw_data_path: "../data/raw/sample.jsonl"
output_path: "../data/processed/clean_data.jsonl"
model_path: "../models/lid.176.ftz"

# 过滤参数
min_length: 100
max_length: 30000
symbol_ratio: 0.3 # 特殊符号占比阈值

# 去重参数
lsh_threshold: 0.8
num_perm: 128
